name = "smarthub"
pages_build_output_dir = "./public"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "smarthub"
database_id = "smarthub-db"

# Cron Scheduler — auto-publish setiap menit
[[triggers]]
crons = ["* * * * *"]

[env.production]
pages_build_output_dir = "./public"

[env.development]
pages_build_output_dir = "./public"
